# Generated by Django 4.2 on 2023-07-31 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_newblog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newblog',
            old_name='ud',
            new_name='id1',
        ),
    ]
