# Generated by Django 4.2 on 2023-08-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_ud_newblog_id1'),
    ]

    operations = [
        migrations.AddField(
            model_name='newblog',
            name='username',
            field=models.CharField(default='shubham', max_length=20),
        ),
    ]
